### ISSUE TITLE
FYI I created a bug in rustc that could make expander obsolete

### ISSUE THREAD

**Issue by programmerjake** [drahnr/expander#11]
https://github.com/rust-lang/rust/issues/124860

**Comment by drahnr** [comment]
Thank you for cross posting! Much appreciated!

I think it's a principled issue of code context that is not accessible.

So one would have to somehow provide the _full_ file content _somewhere_ - at least I cannot envision terminal output that'd give me enough context.

Writing files is the easiest I can imagine, temporary on error (rust could do that) or by default (here we are).
For multiple levels of expansion, i.e. crates depending on code generated by another crate, this becomes arduous.

In the end, it doesn't really matter which tool dumps the context to disk for introspection, as long as it dumps enough contenxt.

If this tool gets obsoleted, all the better, one thing less to maintain :clinking_glasses:
