### ISSUE TITLE
formatting races with rustc, causing compile errors to have wrong locations

### ISSUE THREAD

**Issue by programmerjake** [drahnr/expander#9]
when using `Expander::fmt`, rustc often reads the generated file before `rustfmt` has finished running, causing the compile errors to be based on the unformatted code, making the locations not match the formatted code.

This is because `expand_to_file` uses `Command::spawn` instead of `Command::status` or similar and doesn't wait for `rustfmt` to finish before returning.

**Comment by drahnr** [comment]
Thank you for filing the issue! I encountered the issue very sporadically but didn't get around to debug it.

Would you'd like to create a PR? Otherwise I'll do it in a few hours.

Note that a failure to format should only emit a warning, and not break compilation

**Comment by drahnr** [comment]
@programmerjake could you give #10 a spin, it does work for me.

If I don't hear back from you by Monday, I'll cut a `2.1.0` release including PR #10.
